Acquire course data
course-network/degree-requirement-tree pull request #4
Opened 2019-06-15 18:24 UTC by wilsonia

2019-06-21 01:45 UTC, ianbrown9475 requested changes
Looks good overall and I got it to work successfully. Since we shouldn't need to run the scripts that often, they should be fine as they are. If that ever changes, we should look into using asynchronous requests

2019-06-21 01:45 UTC, ianbrown9475 commented on catalog_data_acquisition/requirements.txt
> +beautifulsoup4==4.7.1
Could you also add `requests`?

2019-06-21 01:45 UTC, ianbrown9475 commented on catalog_data_acquisition/get_courses.py
> +                if block.find('strong').get_text() == 'Prerequisites:':
You should be able to replace these nested ifs with `and` statements

2019-07-19 22:21 UTC, ianbrown9475 commented
Webhook test comment

2019-07-23 07:06 UTC, wilsonia commented
Thanks @ianbrown9475 , I've implemented suggestions on the introduce-or-nodes branch. Since that one was branched from this and this branch has gone idle, I'll close this PR to focus on (this one)[https://github.com/course-network/network-visualization/pull/6] instead

2019-07-23 07:07 UTC, closed without merging